version: "3.9"

services:
  backend:
    restart: always
    container_name: kpd-backend
    build: 
      context: backend
      dockerfile: Dockerfile
    image: kpd-backend
    ports:
      - 3000:3000
    networks:
      - backend
    env_file:
      - .env
  
  frontend:
    container_name: kpd-frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    image: kpd-frontend
    ports:
      - 8080:80
    networks:
      - frontend
  
  postgres: 
    container_name: postgres
    restart: always
    image: postgres
    volumes:
      - postgres-data:/data/postgres
    networks:
      - backend
    env_file:
      - .env

volumes:
  postgres-data: 

networks:
  frontend:
  backend: